// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: omni/omni/observe_vote.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ObserveVote struct {
	Index     uint64                                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Voter     string                                 `protobuf:"bytes,2,opt,name=voter,proto3" json:"voter,omitempty"`
	Round     uint64                                 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Value     github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,4,opt,name=value,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"value"`
	Timestamp time.Time                              `protobuf:"bytes,5,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
}

func (m *ObserveVote) Reset()         { *m = ObserveVote{} }
func (m *ObserveVote) String() string { return proto.CompactTextString(m) }
func (*ObserveVote) ProtoMessage()    {}
func (*ObserveVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa9cccb82aecaf3e, []int{0}
}
func (m *ObserveVote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ObserveVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ObserveVote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ObserveVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObserveVote.Merge(m, src)
}
func (m *ObserveVote) XXX_Size() int {
	return m.Size()
}
func (m *ObserveVote) XXX_DiscardUnknown() {
	xxx_messageInfo_ObserveVote.DiscardUnknown(m)
}

var xxx_messageInfo_ObserveVote proto.InternalMessageInfo

func (m *ObserveVote) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ObserveVote) GetVoter() string {
	if m != nil {
		return m.Voter
	}
	return ""
}

func (m *ObserveVote) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *ObserveVote) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*ObserveVote)(nil), "omni.omni.ObserveVote")
}

func init() { proto.RegisterFile("omni/omni/observe_vote.proto", fileDescriptor_fa9cccb82aecaf3e) }

var fileDescriptor_fa9cccb82aecaf3e = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x50, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x65, 0xb5, 0x18, 0xa1, 0x27, 0x49, 0x0f, 0x84, 0x98, 0x85, 0x78, 0x30, 0x24, 0xc6, 0xdd,
	0x44, 0xff, 0x80, 0x78, 0xf1, 0x64, 0x42, 0x8c, 0x07, 0x2f, 0xa6, 0x94, 0x15, 0x89, 0x85, 0x21,
	0xec, 0x42, 0xea, 0x5f, 0xf4, 0xb3, 0x7a, 0xec, 0x51, 0x3d, 0x54, 0x03, 0x3f, 0x62, 0x76, 0xc7,
	0xea, 0x65, 0x77, 0xde, 0x9b, 0x37, 0xf3, 0xf2, 0xc6, 0x3d, 0x85, 0xaa, 0x2e, 0x39, 0x3e, 0x99,
	0x14, 0x6d, 0x2f, 0x9e, 0x7a, 0x50, 0x82, 0x35, 0x2d, 0x28, 0xf0, 0x1c, 0xdd, 0x60, 0xfa, 0x09,
	0xc2, 0x02, 0xa0, 0x58, 0x0a, 0x6e, 0x1a, 0x59, 0xf7, 0xcc, 0x55, 0x59, 0x09, 0xa9, 0xe6, 0x55,
	0x83, 0xda, 0x60, 0x56, 0x40, 0x01, 0xa6, 0xe4, 0xba, 0x42, 0xf6, 0xec, 0x83, 0xb8, 0xd3, 0x3b,
	0x5c, 0xfc, 0x00, 0x4a, 0x78, 0x33, 0xd7, 0x2e, 0xeb, 0x5c, 0xac, 0x7c, 0x12, 0x91, 0x78, 0x92,
	0x22, 0xd0, 0xac, 0x76, 0x6d, 0xfd, 0x83, 0x88, 0xc4, 0x4e, 0x8a, 0x40, 0xb3, 0x2d, 0x74, 0x75,
	0xee, 0x1f, 0xa2, 0xd6, 0x00, 0xef, 0xc6, 0xb5, 0xfb, 0xf9, 0xb2, 0x13, 0xfe, 0x44, 0x6b, 0x13,
	0xb6, 0xd9, 0x85, 0xd6, 0xe7, 0x2e, 0x3c, 0x2f, 0x4a, 0xf5, 0xd2, 0x65, 0x6c, 0x01, 0x15, 0x5f,
	0x80, 0xac, 0x40, 0xfe, 0x7e, 0x97, 0x32, 0x7f, 0xe5, 0xea, 0xad, 0x11, 0x92, 0xdd, 0xd6, 0x2a,
	0xc5, 0x61, 0x2f, 0x71, 0x9d, 0xbf, 0x00, 0xbe, 0x1d, 0x91, 0x78, 0x7a, 0x15, 0x30, 0x8c, 0xc8,
	0xf6, 0x11, 0xd9, 0xfd, 0x5e, 0x91, 0x1c, 0x6b, 0x97, 0xf5, 0x57, 0x48, 0xd2, 0xff, 0xb1, 0xe4,
	0x62, 0x33, 0x50, 0xb2, 0x1d, 0x28, 0xf9, 0x1e, 0x28, 0x59, 0x8f, 0xd4, 0xda, 0x8e, 0xd4, 0x7a,
	0x1f, 0xa9, 0xf5, 0x78, 0x62, 0x0e, 0xba, 0xc2, 0xbb, 0x1a, 0xef, 0xec, 0xc8, 0x6c, 0xbd, 0xfe,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x48, 0x96, 0x5b, 0x71, 0x01, 0x00, 0x00,
}

func (m *ObserveVote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ObserveVote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ObserveVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintObserveVote(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x2a
	{
		size := m.Value.Size()
		i -= size
		if _, err := m.Value.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintObserveVote(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.Round != 0 {
		i = encodeVarintObserveVote(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Voter) > 0 {
		i -= len(m.Voter)
		copy(dAtA[i:], m.Voter)
		i = encodeVarintObserveVote(dAtA, i, uint64(len(m.Voter)))
		i--
		dAtA[i] = 0x12
	}
	if m.Index != 0 {
		i = encodeVarintObserveVote(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintObserveVote(dAtA []byte, offset int, v uint64) int {
	offset -= sovObserveVote(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ObserveVote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovObserveVote(uint64(m.Index))
	}
	l = len(m.Voter)
	if l > 0 {
		n += 1 + l + sovObserveVote(uint64(l))
	}
	if m.Round != 0 {
		n += 1 + sovObserveVote(uint64(m.Round))
	}
	l = m.Value.Size()
	n += 1 + l + sovObserveVote(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovObserveVote(uint64(l))
	return n
}

func sovObserveVote(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozObserveVote(x uint64) (n int) {
	return sovObserveVote(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ObserveVote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowObserveVote
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ObserveVote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ObserveVote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObserveVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthObserveVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Voter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObserveVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthObserveVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthObserveVote
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthObserveVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipObserveVote(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthObserveVote
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipObserveVote(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowObserveVote
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthObserveVote
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupObserveVote
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthObserveVote
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthObserveVote        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowObserveVote          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupObserveVote = fmt.Errorf("proto: unexpected end of group")
)
